######################
#  PostController    #
######################
empty_path:
  path: /
  controller: App\Controller\PostsController::emptyPath
  requirements: {_locale: '%router.locales%'}

blog_posts:
  path: /{_locale}/posts/{page}/{results_per_page}/{display_order}/{date_sort_order}
  controller: App\Controller\PostsController::posts
  defaults:
    page: 1
    results_per_page: 10
    display_order: 'created_at'
    date_sort_order: 'DESC'
  requirements:
    _locale: '%router.locales%'
    page: '\d+'


blog_search:
  path: /{_locale}/posts/search
  controller: App\Controller\PostsController::search
  requirements: {_locale: '%router.locales%'}

new_blog_post:
  path: /{_locale}/posts/new
  controller: App\Controller\PostsController::new
  requirements: {_locale: '%router.locales%'}

blog_post_edit:
  path: /{_locale}/posts/{slug}/edit
  controller: App\Controller\PostsController::edit
  requirements: {_locale: '%router.locales%'}

blog_post_delete:
  path: /{_locale}/posts/{slug}/delete
  controller: App\Controller\PostsController::delete
  requirements: {_locale: '%router.locales%'}

blog_show:
  path: /{_locale}/posts/{slug}
  controller: App\Controller\PostsController:post
  requirements: {_locale: '%router.locales%'}

##########################
#   SecurityController   #
##########################
login:
  path: /{_locale}/login
  controller: App\Controller\SecurityController::login
  requirements: {_locale: '%router.locales%'}

logout:
  path: /{_locale}/logout
  controller: App\Controller\SecurityController::logout
  requirements: {_locale: '%router.locales%'}

#########################
#    OAuthController    #
#########################
connect_google_start:
  path: /{_locale}/connect/google
  controller: App\Controller\OAuthController::redirectToGoogleConnect
  requirements: {_locale: '%router.locales%'}

google_auth:
  path: /{_locale}/google/auth
  controller: App\Controller\OAuthController::connectGoogleCheck
  requirements: {_locale: '%router.locales%'}

connect_github_start:
  path: /{_locale}/connect/github
  controller: App\Controller\OAuthController::redirectToGithubConnect
  requirements: {_locale: '%router.locales%'}

github_auth:
  path: /{_locale}/github/auth
  controller: App\Controller\OAuthController::authenticateGithubUser
  requirements: {_locale: '%router.locales%'}
